### ISSUE TITLE
Add publishing to Maven

### ISSUE THREAD

**Issue by JFCote** [OpenAPITools/openapi-style-validator#10]
@jmini and @wing328 . I will need your input on how to do this and I guess I will need some access key to be able to publish as "openapitools".

Just give me some examples and I should be able to get it running :)

**Comment by jmini** [comment]
https://github.com/OpenAPITools/empoa/ is doing it from a gradle build.

But I have noticed, I did not introduce the `de.marcphilipp.nexus-publish` and `io.codearte.nexus-staging` plugins yet.

The release step (signing) work only on a computer where the signing is configured.
It is not the case on travis.

**Comment by JFCote** [comment]
@jmini Is this something normal (or even wanted) that the release steps only work on a local computer instead of Travis?

**Comment by jmini** [comment]
No not really, but if you want to perform a release on Travis, you must store the secret to sign your artifact there. 

I know how it is solved with Maven for OpenAPI-Generator.
If somebody knows how to do solve it for Gradle, we can do it for all our projects.

**Comment by jmini** [comment]
For the `groupId` should we use `org.openapitools.openapistylevalidator`?

Then for the artifactId, we can use `openapi-style-validator-` as prefix
* `openapi-style-validator-lib`
* `openapi-style-validator-cli`
* `openapi-style-validator-maven-plugin`
* `openapi-style-validator-gradle-plugin`

---

Ref:
* [Guide to naming conventions on groupId, artifactId, and version](https://maven.apache.org/guides/mini/guide-naming-conventions.html)
* [Maven artifact and groupId naming](https://stackoverflow.com/questions/3724415/maven-artifact-and-groupid-naming)

**Comment by JFCote** [comment]
@jmini Make sense to me. 
Maybe ask @wing328 his advice :)

**Comment by wing328** [comment]
Sounds good to me as well

**Comment by JFCote** [comment]
@jmini can we consider this done?

**Comment by jmini** [comment]
@JFCote: I think this can be closed, each release is on maven central. See:
https://github.com/OpenAPITools/openapi-style-validator#releases-on-maven-central
