### ISSUE TITLE
separate the header naming convention from parameterNamingConvention

### ISSUE THREAD

**Issue by mohamed-el-habib** [OpenAPITools/openapi-style-validator#135]
Validation fail when for api that use the `Accept-Language` header with error "Accept-Language' -> parameter should be in camelCase"

I want to use camelCase for query param and path param. for header this is not possible standard headers have 'Accept-Language' or 'ACCEPT-LANGUAGE' as format.

Maybe we should add headerNamingConvention

Thanks

**Comment by JFCote** [comment]
@mohamed-el-habib This is a good idea! Thanks for the suggestion. If you want to try and create a pull request, it will be more than welcome. Otherwise, I think it might be done in early 2021 since I'm pretty busy at the moment.

**Comment by JFCote** [comment]
Fixed in #141
