### ISSUE TITLE
Maven generates warnings during parallel builds

### ISSUE THREAD

**Issue by baurchanu** [OpenAPITools/openapi-style-validator#155]
Hi, Maven generates warnings during [parallel builds](https://cwiki.apache.org/confluence/display/MAVEN/Parallel+builds+in+Maven+3).

Log:
11:10:47,426 [BuilderThread 4] [WARNING] The following plugins are not marked @threadSafe in `*some-project-name*`:
11:10:47,430 [BuilderThread 4] [WARNING] org.openapitools.openapistylevalidator:openapi-style-validator-maven-plugin:1.4

As far as I figured out, the lib and the plugin are threadsafe. So, I propose to switch `threadsafe` value in the Mojo annotation.

**Comment by JFCote** [comment]
The project itself is running on a single thread so I think it's threadsafe too.
