### ISSUE TITLE
Add test for `OpenApiSpecStyleValidator` in the `core` module.

### ISSUE THREAD

**Issue by JFCote** [OpenAPITools/openapi-style-validator#16]
I was wondering but you do not have any test for `OpenApiSpecStyleValidator` in the `core` module.

I think it would be interesting to have 1 or 2 simple cases tested.

In order to do so, you can:
* Work with: spec files + `swagger-parser` + `empoa-swagger-core` (as you do in the cli)
* Work with an other implementation of the Eclipse-MP-OpenAPI. I have written one that is implementing the interfaces as simple POJO. If you decided to go for this you will need to create the OpenAPI instance with code (which is possible).

If you are interested by the second approach, I can give you more pointers.

_Originally posted by @jmini in https://github.com/OpenAPITools/openapi-style-validator/pull/11#issuecomment-510757339_

**Comment by jmini** [comment]
In #31, an example of a test that could be useful.

**Comment by jmini** [comment]
We have `OpenApiSpecStyleValidatorTest`:
https://github.com/OpenAPITools/openapi-style-validator/blob/master/lib/src/test/java/org/openapitools/openapistylevalidator/OpenApiSpecStyleValidatorTest.java

I think this can be closed.
