### ISSUE TITLE
Add maven and gradle plugins to check during builds

### ISSUE THREAD

**Issue by jmini** [OpenAPITools/openapi-style-validator#20]
Quoting @PierreBesson [on twitter](https://twitter.com/pibesson/status/1151156592840232967):

> once the maven/gradle plugins are available, I would really like to see this in jhipster. Ping @cbornet 

In addition to `cli` we could produce maven and gradle plugin that perform the validation checks and let the build fail if one rule is not respected anymore.

**Comment by JFCote** [comment]
Yes that would be awesome! I will need help from the community because I've never made gradle/maven plugins before!

**Comment by PierreBesson** [comment]
Good luck @JFCote,I also lack experience developing serious maven/gradle plugins but I'm ready to help test/review your PR.

**Comment by jmini** [comment]
I think it is possible to create a maven plugin inside a gradle build with the plugin [`com.liferay.maven.plugin.builder`](https://plugins.gradle.org/plugin/com.liferay.maven.plugin.builder).

Creation of the gradle plugin should be straight forward.

I can give this task a try.

**Comment by JFCote** [comment]
@jmini Please give it a try when you will have time. Thanks!
