### ISSUE TITLE
Need Logo

### ISSUE THREAD

**Issue by JFCote** [OpenAPITools/openapi-style-validator#22]
Anyone with talent want to try something? Could remind of OpenAPI Generator.
Any help appreciated

**Comment by wing328** [comment]
@jimschubert  decided the first logo for us so he may have better suggestions on the logo design

**Comment by zuurw** [comment]
> Anyone with talent want to try something? Could remind of OpenAPI Generator.
> Any help appreciated

Hi @JFCote, if you want I can make one for this project.
Greetings!

**Comment by JFCote** [comment]
@zuurw Of course! :)

**Comment by JFCote** [comment]
@zuurw Did you have time to look at this?

**Comment by JFCote** [comment]
@jmini I have created a logo very quickly using an online tool. It's not perfect, it's low resolution (will only work as a thumbnail) but I suggest we start with that. If it's ok, I will create a PR and add it to the readme + documentation website.

Here it is:

![f9303797-15bc-44f9-9440-89de55368d6e_200x200](https://user-images.githubusercontent.com/14336900/89528544-35d08100-d7b9-11ea-86ce-490fba1ce66b.png)

**Comment by jmini** [comment]
Works for me… And I guess we can still change it if somebody (with design skills) creates something better.

**Comment by JFCote** [comment]
yes! of course!!!
