### ISSUE TITLE
Validation for multiple Spec files in the same repository

### ISSUE THREAD

**Issue by jabrena** [OpenAPITools/openapi-style-validator#294]
**Is your feature request related to a problem? Please describe.**
I am reviewing the project and I don´t find a way to validate multiple openapi files in the same iteration.

**Example:**

```xml
            <plugin>
                <groupId>org.openapitools.openapistylevalidator</groupId>
                <artifactId>openapi-style-validator-maven-plugin</artifactId>
                <version>1.7</version>
                <configuration>
                    <inputFile>${project.basedir}/spec/spec1.yaml</inputFile>
                    <inputFile>${project.basedir}/spec/spec2.yaml</inputFile>
                    <validateInfoLicense>false</validateInfoLicense>
                    <validateInfoDescription>true</validateInfoDescription>
                    <validateInfoContact>false</validateInfoContact>
                    <validateOperationOperationId>true</validateOperationOperationId>
                    <validateOperationDescription>true</validateOperationDescription>
                    <validateOperationTag>true</validateOperationTag>
                    <validateOperationSummary>true</validateOperationSummary>
                    <validateModelPropertiesExample>false</validateModelPropertiesExample>
                    <validateModelNoLocalDef>true</validateModelNoLocalDef>
                    <pathNamingConvention>UnderscoreCase</pathNamingConvention>
                    <parameterNamingConvention>UnderscoreCase</parameterNamingConvention>
                    <headerNamingConvention>UnderscoreCase</headerNamingConvention>
                    <propertyNamingConvention>UnderscoreCase</propertyNamingConvention>
                    <validateNaming>true</validateNaming>
                    <ignoreHeaderXNaming>true</ignoreHeaderXNaming>
                </configuration>
                <executions>
                    <execution>
                        <id>validate</id>
                        <phase>validate</phase>
                        <goals>
                            <goal>validate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

Currently, if I execute:

```
mvn clean validate
```

The plugin only validates the second openapi file.

**Describe the solution you'd like**

Adding a new parameter like:

```xml
<inputFolder>${project.basedir}/spec/</inputFolder>
```

Could be enough to process all spec files stored in that path.

Many thanks in advance

Juan Antonio

**Comment by jabrena** [comment]
I have a question if exist by command line a way to change the parameter `inputFile`by command line.

**Comment by jabrena** [comment]
One workaround that I found is using Executions:

```xml
                <executions>
                    <execution>
                        <id>spec1</id>
                        <phase>validate</phase>
                        <goals>
                            <goal>validate</goal>
                        </goals>
                        <configuration>
                            <inputFile>${project.basedir}/spec/spec1.yaml</inputFile>
                            <validateInfoLicense>false</validateInfoLicense>
                            <validateInfoDescription>true</validateInfoDescription>
                            <validateInfoContact>false</validateInfoContact>
                            <validateOperationOperationId>true</validateOperationOperationId>
                            <validateOperationDescription>false</validateOperationDescription><!-- * -->
                            <validateOperationTag>true</validateOperationTag>
                            <validateOperationSummary>true</validateOperationSummary>
                            <validateModelPropertiesExample>false</validateModelPropertiesExample>
                            <validateModelNoLocalDef>true</validateModelNoLocalDef>
                            <pathNamingConvention>HyphenCase</pathNamingConvention>
                            <parameterNamingConvention>CamelCase</parameterNamingConvention>
                            <headerNamingConvention>UnderscoreCase</headerNamingConvention>
                            <propertyNamingConvention>CamelCase</propertyNamingConvention>
                            <validateNaming>false</validateNaming>
                            <ignoreHeaderXNaming>true</ignoreHeaderXNaming>
                        </configuration>
                    </execution>
                    <execution>
                        <id>spec2</id>
                        <phase>validate</phase>
                        <goals>
                            <goal>validate</goal>
                        </goals>
                        <configuration>
                            <inputFile>${project.basedir}/spec/spec2.yaml</inputFile>
                            <validateInfoLicense>false</validateInfoLicense>
                            <validateInfoDescription>true</validateInfoDescription>
                            <validateInfoContact>false</validateInfoContact>
                            <validateOperationOperationId>true</validateOperationOperationId>
                            <validateOperationDescription>false</validateOperationDescription><!-- * -->
                            <validateOperationTag>true</validateOperationTag>
                            <validateOperationSummary>true</validateOperationSummary>
                            <validateModelPropertiesExample>false</validateModelPropertiesExample>
                            <validateModelNoLocalDef>true</validateModelNoLocalDef>
                            <pathNamingConvention>HyphenCase</pathNamingConvention>
                            <parameterNamingConvention>CamelCase</parameterNamingConvention>
                            <headerNamingConvention>UnderscoreCase</headerNamingConvention>
                            <propertyNamingConvention>CamelCase</propertyNamingConvention>
                            <validateNaming>false</validateNaming>
                            <ignoreHeaderXNaming>true</ignoreHeaderXNaming>
                        </configuration>
                    </execution>
                </executions>
```

**Comment by JFCote** [comment]
@jabrena I would like to know more about your use case since it's the first time I encounter this.

In normal cases, you should have only one spec file per project. For example, in my project, I have 6 openapi yaml files but this is only 1 spec. There is the main one (openapi.yml) and it references models or methods in other files (definitions.yml, admin.yml, etc..). In the end, the style validator only needs to know the main specification file and it will crawl the entire spec (using swagger-parser in the background).

If you really have 2 different main specs, meaning they don't have any link together and don't have references between them, I would say that this is a smell. They should not be in the same project IMHO. None of the tools for openapi works for multiple unlinked files.

If you have 2 unlinked openapi, they should be places each in their own sub-module. For example, since you seems to use Maven, they should be in 2 sub-project with each their own POM. That way, you can specify different validation configuration and even generation if you use openapi-generator too.

Hope that makes sense, let me know more about your use case, I'm curious.

**Comment by jabrena** [comment]
Hi @JFCote,

> In normal cases, you should have only one spec per project. For example, in my project, I have 6 openapi yaml files but this is only 1 spec. There is the main one (openapi.yml)

Maybe this is my case but I don´t have the main one. 

Do you have one example about the main `openapi.yml`?

Using this approach, it could solve my issue.

Juan Antonio

**Comment by JFCote** [comment]
Hi @jabrena ,

In fact there is an example in this project itself for the unit tests: https://github.com/OpenAPITools/openapi-style-validator/tree/master/specs/split

This is a 2 files spec. The mains one and the definition ones. They work together and you only have to point to the main one to scan it all.

**Comment by jabrena** [comment]
Hi @JFCote, 

I saw the example but it doesn´t match with scenario that I have.

I will explain my scenario in the following image:

![image](https://user-images.githubusercontent.com/147263/154031636-08fee5fd-a638-457a-af2d-4e8189be88b3.png)

If you observe the service is the sum of multiple API files so, currently, If I have 3 Specs, I need to define 3 profiles in maven to validate the specs, but If the plugin would have an option to define a folder, this feature could reduce the code at maven level. I suppose that it is not a rare scenario.

Juan Antonio

**Comment by JFCote** [comment]
Hi @jabrena,

Your scenario is very common. In this case, one usually creates 3 Maven or Gradle sub-modules. Therefore, if we use your example, you have service X and 3 sub-folders for each micro-services. In inch pom.xml, you can configure the scanning of the associated yaml.

In the end, each sub-modules should have it's own:
- database
- openapi spec
- pom.xml

**Comment by jabrena** [comment]
Yes, but imagine that you store in a repo all specs in isolation. You could have a maven project only used to validate that specs.

**Comment by JFCote** [comment]
@jabrena You could but this is not supported right now and I'm not convinced there is high demand on this. If you want to propose a PR, I will review it. In the meantime, I will let this task open.

**Comment by jabrena** [comment]
Hi @JFCote, 

> If you want to propose a PR, I will review it. 

Oki, I will review the project internally in coming weeks. Let`s go in that direction.

Juan Antonio

**Comment by JFCote** [comment]
@jabrena I didn't hear back from you and I have read the entire thread once again. I'm totally convinced that one Maven/Gradle project should have only one OpenAPI Spec. Each services should have their own API, thus their own OpenAPI specification.

Also, if you want to use other tools like OpenAPI Generator, it will only work with one file at the time.

I've decided to close this issue to follow the good practices of other tools. If one day you provide a PR and it doesn't break anything, I will consider merging it as an "experimental feature".

I hope you understand my decision. If you want guidance on how to refactor your project, I suggest you re-read my comments in this thread. Thanks
