### ISSUE TITLE
is any tools with validate the openApi param by the Java annotation of io.swagger.v3.oas.annotations.media.Schema

### ISSUE THREAD

**Issue by leland17** [OpenAPITools/openapi-style-validator#332]
is any tools with validate the openApi param by the Java annotation of io.swagger.v3.oas.annotations.media.Schema

**Comment by JFCote** [comment]
@leland17 I'm not sure I  understand your question / issue. Can you please explain with an example? Thanks

**Comment by leland17** [comment]
> @leland17 I'm not sure I understand your question / issue. Can you please explain with an example? Thanks

sorry.  I found the solution, using the networknt/json-schema-validator. thanks
 https://github.com/networknt/json-schema-validator

**Comment by JFCote** [comment]
Ok. Closing this.
