### ISSUE TITLE
CLI version not working

### ISSUE THREAD

**Issue by jmini** [OpenAPITools/openapi-style-validator#36]
After the merge of https://github.com/OpenAPITools/openapi-style-validator/pull/35, I have the feeling that this code is not working:

https://github.com/OpenAPITools/openapi-style-validator/blob/dcfb502049d1a60009b9960c4cd416cc90c29d74/cli/src/main/java/org/openapitools/openapistylevalidator/OutputUtils.java#L41-L44

I get always `DEVELOPMENT` with the shadow jar.

To reproduce. Run:

```
./gradlew build
```

And:
```
java -jar cli/build/libs/openapi-style-validator-cli-<version>.jar -v
Current version: DEVELOPMENT
```

**Comment by JFCote** [comment]
@jmini I forgot to test it yesterday. It's normal that it shows `DEVELOPMENT` in the IDE but it should work with the Jar. Thanks for opening the issue. I'll try to look at it today!
