### ISSUE TITLE
Cannot generate the jar openapi-style-validator-cli-1.0.jar file

### ISSUE THREAD

**Issue by shripal7** [OpenAPITools/openapi-style-validator#5]
Hi, 
I ran the commands mentioned in readme with old github commit e8ecda524c4f516e1368920c0b1cd95933a465eb, and it runs fine.
But with new build against the latest commit ( ea18d422e64d3a80704f9168b43b62384a4e9258) the openapi-style-validator-cli-1.0.jar is not generated.

**Comment by JFCote** [comment]
@shripal7 I have just tested it and I have no problem generating the cli with the latest version. Can you update and try it?

By the way, in the next couple of weeks / months, the project will be updated and we should have a maven release up and running so you will not have to compile it with the source code.

I have no ETA but this is coming. :)

Have a nice day.
