### ISSUE TITLE
Pascal Case Support

### ISSUE THREAD

**Issue by dchauhan-twilio** [OpenAPITools/openapi-style-validator#520]
**Is your feature request related to a problem? Please describe.**
Would like to be able to use this tool to validate and enforce PascalCase. 

**Describe the solution you'd like**
I want to be able to run this validation tool and verify that path params are PascalCase.

**Describe alternatives you've considered**
Looked into camelCase but this does not align with what we need.

**Additional context**
If I have understood the code correctly, [`NamingValidator.java`](https://github.com/OpenAPITools/openapi-style-validator/blob/HEAD/lib/src/main/java/org/openapitools/openapistylevalidator/NamingValidator.java#L6) needs to be updated with an `isPascalCase(...)` method and regex to back this, and then exposed as an option in [`ValidatorParameters.java`](https://github.com/OpenAPITools/openapi-style-validator/blob/HEAD/lib/src/main/java/org/openapitools/openapistylevalidator/ValidatorParameters.java). With some guidance, would be happy to submit a PR.

**Comment by JFCote** [comment]
Hi @dchauhan-twilio! I think what you are looking at is `HyphenCase`. This is the default validator used for path! :)

https://github.com/OpenAPITools/openapi-style-validator/blob/master/README.md?plain=1#L109

Let me know if this fixes your issue!

**Comment by dchauhan-twilio** [comment]
Hi @JFCote thank for the update.  Looking at `HyphenCase`, if we took the example of "page size", then with `HyphenCase` would it not be `page-size`, and with `HyphenUpperCase` it would be `Page-Size`, right? What we are after is the convention `PageSize`.

**Comment by JFCote** [comment]
@dchauhan-twilio Oh you are right. I answered before my first coffee! Let me check this again this afternoon.

**Comment by dchauhan-twilio** [comment]
Awesome. I'll use the approach you suggested and try to create a PR. Will reach out if I run into any problems.

Yea we are looking into using this tool to ensure consistently.

**Comment by JFCote** [comment]
@dchauhan-twilio Nice to know! Just finished reading "Ask Your Developer" by your CEO Jeff Lawson. It was awesome and would love help Twilio with my open-source project!

**Comment by JFCote** [comment]
Fixed by #521
