### ISSUE TITLE
Change "Naming Strategy" to "Naming Convention"

### ISSUE THREAD

**Issue by JFCote** [OpenAPITools/openapi-style-validator#56]
Very important to stay backward compatible for a while. Maybe add a warning log when people use the old one and say it will be deleted in a future version.

**Comment by jmini** [comment]
With the same move, I suggest to rename `appelation` to `designation`: 
https://github.com/OpenAPITools/openapi-style-validator/blob/c96cc4802156b385a672e131e86e6fbbff1582c5/lib/src/main/java/org/openapitools/openapistylevalidator/ValidatorParameters.java#L10-L18

**Comment by JFCote** [comment]
@jmini That make sense
