### ISSUE TITLE
Identify possible users of OpenAPI Style Validator

### ISSUE THREAD

**Issue by JFCote** [OpenAPITools/openapi-style-validator#63]
This thread is to identify possible users of our project.

On the top of my head, I can identify a few:

- [OpenAPI Generator](https://github.com/OpenAPITools/openapi-generator) who could integrate our gradle/maven plugin to validate the style of all the files used for input for the samples. That way, the project could garante that all input follow the same convention.
- All the Text Editors could possibly want to use our library natively or we could create plugins for them: https://openapi.tools/#text-editors
- Other? Please suggest ideas below.

This is an open discussion, please share any ideas. Also, if your project is using our project, please let us know!

**Comment by gervaisb** [comment]
We are using it inside our CI. Each time the specification changes, both _openapi-generator-cli_ and _openapi-style-validator_  are run against it.

**Comment by JFCote** [comment]
@gervaisb Thanks for the info!

**Comment by JFCote** [comment]
Closing this discussion and creating a new one in the new Discussion tab to know our user more!
https://github.com/OpenAPITools/openapi-style-validator/discussions/236
