### ISSUE TITLE
Schema name validation in Maven plugin release

### ISSUE THREAD

**Issue by thdb-theo** [OpenAPITools/openapi-style-validator#690]
**Is your feature request related to a problem? Please describe.**
I would like to use the schema name validation with the Maven Plugin. I can see that the feature was added after the most recent release. [The commit](https://github.com/OpenAPITools/openapi-style-validator/commit/2583437295031b8a17f5e3d4310dacbff3427555) is from September, and the latest release is from August.

**Describe the solution you'd like**
A new release of the Maven plugin with schema name validation.

**Describe alternatives you've considered**
N/A
**Additional context**
N/A

**Comment by JFCote** [comment]
Hi @thdb-theo ! I will request a release since I don't control this.

@wing328 Can you please create a release when you will have the time? Thanks!

**Comment by wing328** [comment]
I'll try this weekend.

**Comment by thdb-theo** [comment]
Hey guys, thanks for looking into this. Any news on the release?

**Comment by JFCote** [comment]
@thdb-theo The release was done on Sunday! Sorry forgot about updating you. Can you go and check it out? Thanks!

**Comment by thdb-theo** [comment]
Oh amazing! Thank you 😀
