### ISSUE TITLE
Recursive property name validation feature

### ISSUE THREAD

**Issue by tothgergely92** [OpenAPITools/openapi-style-validator#694]
**Is your feature request related to a problem? Please describe.**
I would like to use the validator to validate property names recursively in nested objects.

**Describe the solution you'd like**
Validator should validate property names even in nested objects.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by JFCote** [comment]
@tothgergely92 Thanks for this feature request. I see you have created a PR for this. I will try to take a look next week!
