### ISSUE TITLE
Migration to OpenAPI v3

### ISSUE THREAD

**Issue by jmini** [OpenAPITools/openapi-style-validator#7]
Right now the core project `modules/lib` has a dependency on:

```gradle
compile group: 'io.swagger', name: 'swagger-parser', version: '1.0.33'
```

This is for OpenAPI v2.

---

During the update to OpenAPI v3, it would be great to consider for the core module to have only a dependency on:

```gradle
compile group: 'org.eclipse.microprofile.openapi', name: 'microprofile-openapi-api', version: '2.0-MR1'
```

This way, different parsers can be used, and the code is not coupled to `swagger-parser` and/or `swagger-core`.

The cli can still use swagger-parser to parse OpenAPI v2 and v3 specifications. To wrap a `swagger-core` instance into an interface of the  `org.eclipse.microprofile.openapi.models` package, the project [empoa](https://openapitools.github.io/empoa/) can be used.

**Comment by JFCote** [comment]
@jmini When you'll be back, I will need your help getting started with this EMPOA thing. I can't find any example code on how to convert a string spec and convert it to the microprofile object. In the example, there is a `parserResult` object and it's not clear how to get this.

**Comment by jmini** [comment]
In the "core" project, you need a compile dependency on `org.eclipse.microprofile.openapi:microprofile-openapi-api:2.0-MR1`.

In the "cli" project, you need a compile dependency on:

* Swagger-Parser: `io.swagger.parser.v3:swagger-parser:2.0.13`
* Empoa: `org.openapitools.empoa:empoa-swagger-core:1.0.0`

In the CLI project you will be able to parse and convert the API:

```java
// use Swagger-Parser to instantiate Swagger-Core:
OpenAPIParser openApiParser = new OpenAPIParser();
ParseOptions options = new ParseOptions();

SwaggerParseResult parserResult = openApiParser.readContents(jsonOrYaml, null, options);
io.swagger.v3.oas.models.OpenAPI swaggerOpenAPI = parserResult.getOpenAPI();

// convert to Eclipse-MicroProfile:
org.eclipse.microprofile.openapi.models.OpenAPI openAPI = SwAdapter.toOpenAPI(swaggerOpenAPI);
```

And pass it to your core module.

**Comment by JFCote** [comment]
@jmini Thanks I will try it this week and put you as reviewer.

**Comment by JFCote** [comment]
Blocked by this bug: https://github.com/swagger-api/swagger-parser/issues/1149
