### ISSUE TITLE
Remove Travis Integration and use only Github Actions?

### ISSUE THREAD

**Issue by JFCote** [OpenAPITools/openapi-style-validator#72]
See what are the effect of this.

**Comment by JFCote** [comment]
- Travis support testing the compilation on multiple java version. Is it supported in Github action?
- Our badges are driven by Travis. Can we make them work with Github action?
- Other?

@jmini ? Any idea what we need to watch regarding this?

**Comment by jmini** [comment]
I never used GitHub action myself yet…

**Comment by jmini** [comment]
@sullis did the change in an other repo of this organization. This can probably be used as template:

* https://github.com/OpenAPITools/empoa/pull/8: addition GitHub Actions
* https://github.com/OpenAPITools/empoa/pull/11: removal Travis CI

One thing I think we have with Travis CI in this repo is the push of SNAPSHOTS versions to Sonatype OSS repo. But I can't imagine this is not possible with GitHub Actions.

**Comment by JFCote** [comment]
@jmini Yeah I'm pretty sure almost everything is possible with Github actions. I just didn't have time so far to check for this. :)

**Comment by JFCote** [comment]
100% github action! We are all good!
